# Aviation Accidents Analysis

You are part of a consulting firm that is tasked to do an analysis of commercial and passenger jet airline safety. The client (an airline/airplane insurer) is interested in knowing what types of aircraft (makes/models) exhibit low rates of total destruction and low likelihood of fatal or serious passenger injuries in the event of an accident. They are also interested in any general variables/conditions that might be at play. Your analysis will be based off of aviation accident data accumulated from the years 1948-2023. 

Our client is only interested in airplane makes/models that are professional builds and could potentially still be active. Assume a max lifetime of 40 years for a make/model retirement and make sure to filter your data accordingly (i.e. from 1983 onwards). They would also like separate recommendations for small aircraft vs. larger passenger models. **In addition, make sure that claims that you make are statistically robust and that you have enough samples when making comparisons between groups.**


In this summative assessment you will demonstrate your ability to:
- **Use Pandas to load, inspect, and clean the dataset appropriately.**
- **Transform relevant columns to create measures that address the problem at hand.**
- conduct EDA: visualization and statistical measures to systematically understand the structure of the data
- recommend a set of airplanes and makes conforming to the client's request and identify at least *two* factors contributing to airplane safety. You must provide supporting evidence (visuals, summary statistics, tables) for each claim you make.

### Make relevant library imports

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Data Loading and Inspection

### Load in data from the relevant directory and inspect the dataframe.
- inspect NaNs, datatypes, and summary statistics

In [5]:
import os
print(os.listdir('data'))

['.gitkeep', 'AviationData.csv', 'USState_Codes.csv']

In [6]:
df = pd.read_csv('data/AviationData.csv', encoding='latin1')

C:\Users\USER\AppData\Local\Temp\ipykernel_2140\2676236454.py:1: DtypeWarning: Columns (0: Latitude, 1: Longitude, 2: Broad.phase.of.flight) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data/AviationData.csv', encoding='latin1')

In [7]:
print("Dataset shape:")
print("df.shape")

print("\nMissing names:")
print(df.columns.tolist())

print("\nMissing values:")
print(df.isnull().sum())

print("\nData types:")
print(df.dtypes)

print("\nSummary statistics:")
display(df.describe(include='all'))

Dataset shape:
df.shape

Missing names:
['Event.Id', 'Investigation.Type', 'Accident.Number', 'Event.Date', 'Location', 'Country', 'Latitude', 'Longitude', 'Airport.Code', 'Airport.Name', 'Injury.Severity', 'Aircraft.damage', 'Aircraft.Category', 'Registration.Number', 'Make', 'Model', 'Amateur.Built', 'Number.of.Engines', 'Engine.Type', 'FAR.Description', 'Schedule', 'Purpose.of.flight', 'Air.carrier', 'Total.Fatal.Injuries', 'Total.Serious.Injuries', 'Total.Minor.Injuries', 'Total.Uninjured', 'Weather.Condition', 'Broad.phase.of.flight', 'Report.Status', 'Publication.Date']

Missing values:
Event.Id                      0
Investigation.Type            0
Accident.Number               0
Event.Date                    0
Location                     52
Country                     226
Latitude                  54507
Longitude                 54516
Airport.Code              38757
Airport.Name              36185
Injury.Severity            1000
Aircraft.damage            3194
Aircraft.Category         56602
Registration.Number        1382
Make                         63
Model                        92
Amateur.Built               102
Number.of.Engines          6084
Engine.Type                7096
FAR.Description           56866
Schedule                  76307
Purpose.of.flight          6192
Air.carrier               72241
Total.Fatal.Injuries      11401
Total.Serious.Injuries    12510
Total.Minor.Injuries      11933
Total.Uninjured            5912
Weather.Condition          4492
Broad.phase.of.flight     27165
Report.Status              6384
Publication.Date          13771
dtype: int64

Data types:
Event.Id                      str
Investigation.Type            str
Accident.Number               str
Event.Date                    str
Location                      str
Country                       str
Latitude                   object
Longitude                  object
Airport.Code                  str
Airport.Name                  str
Injury.Severity               str
Aircraft.damage               str
Aircraft.Category             str
Registration.Number           str
Make                          str
Model                         str
Amateur.Built                 str
Number.of.Engines         float64
Engine.Type                   str
FAR.Description               str
Schedule                      str
Purpose.of.flight             str
Air.carrier                   str
Total.Fatal.Injuries      float64
Total.Serious.Injuries    float64
Total.Minor.Injuries      float64
Total.Uninjured           float64
Weather.Condition             str
Broad.phase.of.flight         str
Report.Status                 str
Publication.Date              str
dtype: object

Summary statistics:

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
count,88889,88889,88889,88889,88837,88663,34382,34373,50132,52704,...,82697,16648,77488.000000,76379.000000,76956.000000,82977.000000,84397,61724,82505,75118
unique,87951,2,88863,14782,27758,219,25592,27156,10374,24870,...,26,13590,NaN,NaN,NaN,NaN,4,12,17074,2924
top,20001214X45071,Accident,ERA22LA103,1982-05-16,"ANCHORAGE, AK",United States,332739N,0112457W,NONE,Private,...,Personal,Pilot,NaN,NaN,NaN,NaN,VMC,Landing,Probable Cause,25-09-2020
freq,3,85015,2,25,434,82248,19,24,1488,240,...,49448,258,NaN,NaN,NaN,NaN,77303,15428,61754,17019
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.647855,0.279881,0.357061,5.325440,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,5.485960,1.544084,2.235625,27.913634,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,0.000000,0.000000,1.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,0.000000,0.000000,2.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,349.000000,161.000000,380.000000,699.000000,NaN,NaN,NaN,NaN

In [ ]:
df.columns.tolist()

['Event.Id',
 'Investigation.Type',
 'Accident.Number',
 'Event.Date',
 'Location',
 'Country',
 'Latitude',
 'Longitude',
 'Airport.Code',
 'Airport.Name',
 'Injury.Severity',
 'Aircraft.damage',
 'Aircraft.Category',
 'Registration.Number',
 'Make',
 'Model',
 'Amateur.Built',
 'Number.of.Engines',
 'Engine.Type',
 'FAR.Description',
 'Schedule',
 'Purpose.of.flight',
 'Air.carrier',
 'Total.Fatal.Injuries',
 'Total.Serious.Injuries',
 'Total.Minor.Injuries',
 'Total.Uninjured',
 'Weather.Condition',
 'Broad.phase.of.flight',
 'Report.Status',
 'Publication.Date']

In [ ]:
display(df[['Event.Date', 'Make', 'Model', 'Aircraft.damage',
          'Aircraft.Category', 'Injury.Severity']].head(10))

print("\nMissing values in relevant columns:")
print(df[['Event.Date', 'Make', 'Model', 'Aircraft.damage',
          'Aircraft.Category', 'Injury.Severity']].isnull().sum())

,Event.Date,Make,Model,Aircraft.damage,Aircraft.Category,Injury.Severity
0,1948-10-24,Stinson,108-3,Destroyed,NaN,Fatal(2)
1,1962-07-19,Piper,PA24-180,Destroyed,NaN,Fatal(4)
2,1974-08-30,Cessna,172M,Destroyed,NaN,Fatal(3)
3,1977-06-19,Rockwell,112,Destroyed,NaN,Fatal(2)
4,1979-08-02,Cessna,501,Destroyed,NaN,Fatal(1)
5,1979-09-17,Mcdonnell Douglas,DC9,Substantial,Airplane,Non-Fatal
6,1981-08-01,Cessna,180,Destroyed,NaN,Fatal(4)
7,1982-01-01,Cessna,140,Substantial,Airplane,Non-Fatal
8,1982-01-01,Cessna,401B,Substantial,Airplane,Non-Fatal
9,1982-01-01,North American,NAVION L-17B,Substantial,NaN,Non-Fatal

Missing values in relevant columns:
Event.Date               0
Make                    63
Model                   92
Aircraft.damage       3194
Aircraft.Category    56602
Injury.Severity       1000
dtype: int64

## Data Cleaning

### Filtering aircrafts and events

We want to filter the dataset to include aircraft that the client is interested in an analysis of:
- inspect relevant columns
- figure out any reasonable imputations
- filter the dataset

In [ ]:
# Inspect relevant columns
relevant_columns = [
    'Event.Date',
    'Make',
    'Model',
    'Aircraft.Category',
    'Aircraft.damage',
    'Injury.Severity',
    'Total.Fatal.Injuries',
    'Total.Serious.Injuries'
]

display(df[relevant_columns].head(10))

print("\nMissing values in relevant columns:")
print(df[relevant_columns].isnull().sum())

print("\nUnique aircraft categories:")
print(df['Aircraft.Category'].value_counts(dropna=False))

print("\nUnique aircraft damage values:")
print(df['Aircraft.damage'].value_counts(dropna=False))

,Event.Date,Make,Model,Aircraft.Category,Aircraft.damage,Injury.Severity,Total.Fatal.Injuries,Total.Serious.Injuries
0,1948-10-24,Stinson,108-3,NaN,Destroyed,Fatal(2),2.0,0.0
1,1962-07-19,Piper,PA24-180,NaN,Destroyed,Fatal(4),4.0,0.0
2,1974-08-30,Cessna,172M,NaN,Destroyed,Fatal(3),3.0,NaN
3,1977-06-19,Rockwell,112,NaN,Destroyed,Fatal(2),2.0,0.0
4,1979-08-02,Cessna,501,NaN,Destroyed,Fatal(1),1.0,2.0
5,1979-09-17,Mcdonnell Douglas,DC9,Airplane,Substantial,Non-Fatal,NaN,NaN
6,1981-08-01,Cessna,180,NaN,Destroyed,Fatal(4),4.0,0.0
7,1982-01-01,Cessna,140,Airplane,Substantial,Non-Fatal,0.0,0.0
8,1982-01-01,Cessna,401B,Airplane,Substantial,Non-Fatal,0.0,0.0
9,1982-01-01,North American,NAVION L-17B,NaN,Substantial,Non-Fatal,0.0,0.0

Missing values in relevant columns:
Event.Date                    0
Make                         63
Model                        92
Aircraft.Category         56602
Aircraft.damage            3194
Injury.Severity            1000
Total.Fatal.Injuries      11401
Total.Serious.Injuries    12510
dtype: int64

Unique aircraft categories:
Aircraft.Category
NaN                  56602
Airplane             27617
Helicopter            3440
Glider                 508
Balloon                231
Gyrocraft              173
Weight-Shift           161
Powered Parachute       91
Ultralight              30
Unknown                 14
WSFT                     9
Powered-Lift             5
Blimp                    4
UNK                      2
Rocket                   1
ULTR                     1
Name: count, dtype: int64

Unique aircraft damage values:
Aircraft.damage
Substantial    64148
Destroyed      18623
NaN             3194
Minor           2805
Unknown          119
Name: count, dtype: int64

In [ ]:
# Inspect relevant columns
relevant_columns = [
    'Event.Date',
    'Make',
    'Model',
    'Aircraft.Category',
    'Aircraft.damage',
    'Injury.Severity',
    'Total.Fatal.Injuries'
]

display(df[relevant_columns].info())
display(df[relevant_columns].isnull().sum())
display(df[relevant_columns].head(10))

<class 'pandas.DataFrame'>
RangeIndex: 88889 entries, 0 to 88888
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Event.Date            88889 non-null  str
 1   Make                  88826 non-null  str
 2   Model                 88797 non-null  str
 3   Aircraft.Category     32287 non-null  str
 4   Aircraft.damage       85695 non-null  str
 5   Injury.Severity       87889 non-null  str
 6   Total.Fatal.Injuries  77488 non-null  float64
dtypes: float64(1), str(6)
memory usage: 8.6 MB

None

Event.Date                  0
Make                       63
Model                      92
Aircraft.Category       56602
Aircraft.damage          3194
Injury.Severity          1000
Total.Fatal.Injuries    11401
dtype: int64

,Event.Date,Make,Model,Aircraft.Category,Aircraft.damage,Injury.Severity,Total.Fatal.Injuries
0,1948-10-24,Stinson,108-3,NaN,Destroyed,Fatal(2),2.0
1,1962-07-19,Piper,PA24-180,NaN,Destroyed,Fatal(4),4.0
2,1974-08-30,Cessna,172M,NaN,Destroyed,Fatal(3),3.0
3,1977-06-19,Rockwell,112,NaN,Destroyed,Fatal(2),2.0
4,1979-08-02,Cessna,501,NaN,Destroyed,Fatal(1),1.0
5,1979-09-17,Mcdonnell Douglas,DC9,Airplane,Substantial,Non-Fatal,NaN
6,1981-08-01,Cessna,180,NaN,Destroyed,Fatal(4),4.0
7,1982-01-01,Cessna,140,Airplane,Substantial,Non-Fatal,0.0
8,1982-01-01,Cessna,401B,Airplane,Substantial,Non-Fatal,0.0
9,1982-01-01,North American,NAVION L-17B,NaN,Substantial,Non-Fatal,0.0

In [ ]:
# Figure out reasonable imputations
print("Aircraft Category:")
print(df['Aircraft.Category'].value_counts(dropna=False))

print("\nAircraft Damage:")
print(df['Aircraft.damage'].value_counts(dropna=False))

print("\nInjury Severity:")
print(df['Injury.Severity'].value_counts(dropna=False))

print("\nTotal Fatal Injuries:")
print(df['Total.Fatal.Injuries'].describe())
print("Missing values:", df['Total.Fatal.Injuries'].isnull().sum())

Aircraft Category:
Aircraft.Category
NaN                  56602
Airplane             27617
Helicopter            3440
Glider                 508
Balloon                231
Gyrocraft              173
Weight-Shift           161
Powered Parachute       91
Ultralight              30
Unknown                 14
WSFT                     9
Powered-Lift             5
Blimp                    4
UNK                      2
Rocket                   1
ULTR                     1
Name: count, dtype: int64

Aircraft Damage:
Aircraft.damage
Substantial    64148
Destroyed      18623
NaN             3194
Minor           2805
Unknown          119
Name: count, dtype: int64

Injury Severity:
Injury.Severity
Non-Fatal     67357
Fatal(1)       6167
Fatal          5262
Fatal(2)       3711
Incident       2219
              ...
Fatal(96)         1
Fatal(114)        1
Fatal(199)        1
Fatal(89)         1
Fatal(57)         1
Name: count, Length: 110, dtype: int64

Total Fatal Injuries:
count    77488.000000
mean         0.647855
std          5.485960
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max        349.000000
Name: Total.Fatal.Injuries, dtype: float64
Missing values: 11401

In [ ]:
print(df['Injury.Severity'].value_counts(dropna=False))

Injury.Severity
Non-Fatal     67357
Fatal(1)       6167
Fatal          5262
Fatal(2)       3711
Incident       2219
              ...
Fatal(96)         1
Fatal(114)        1
Fatal(199)        1
Fatal(89)         1
Fatal(57)         1
Name: count, Length: 110, dtype: int64

In [ ]:
# Filter aircrafts and events

df['Event.Date'] = pd.to_datetime(df['Event.Date'], errors='coerce')

df_filtered = df[
    (df['Aircraft.Category'] == 'Airplane') &
    (df['Amateur.Built'].astype(str).str.strip().str.upper() == 'NO') &
    (df['Event.Date'].dt.year >= 1983)
].copy()

print("Original dataset shape:", df.shape)
print("Filtered dataset shape:", df_filtered.shape)

Original dataset shape: (88889, 31)
Filtered dataset shape: (21447, 31)

In [ ]:
print("Aircraft categories:")
print(df_filtered['Aircraft.Category'].value_counts(dropna=False))

print("\nAmateur-built values:")
print(df_filtered['Amateur.Built'].value_counts(dropna=False))

print("\nEarliest accident date:")
print(df_filtered['Event.Date'].min())

print("\nLatest accident date:")
print(df_filtered['Event.Date'].max())

print("\nFiltered dataset shape:")
print(df_filtered.shape)

Aircraft categories:
Aircraft.Category
Airplane    21447
Name: count, dtype: int64

Amateur-built values:
Amateur.Built
No    21447
Name: count, dtype: int64

Earliest accident date:
1983-03-18 00:00:00

Latest accident date:
2022-12-26 00:00:00

Filtered dataset shape:
(21447, 31)

### Cleaning and constructing Key Measurables

Injuries and robustness to destruction are a key interest point for the client. Clean and impute relevant columns and then create derived fields that best quantifies what the client wishes to track. **Use commenting or markdown to explain any cleaning assumptions as well as any derived columns you create.**

**Construct metric for fatal/serious injuries**

*Hint:* Estimate the total number of passengers on each flight. The likelihood of serious / fatal injury can be estimated as a fraction from this.

In [ ]:


# Construct metric for fatal/serious injuries

# Cleaning assumption:
# Convert fatal injury counts to numeric values.
# Any values that cannot be converted become NaN rather than
# being incorrectly treated as zero.

df_filtered['Total.Fatal.Injuries'] = pd.to_numeric(
    df_filtered['Total.Fatal.Injuries'],
    errors='coerce'
)

# Inspect available passenger and injury columns before
# estimating the total number of passengers and injury rates.
print([
    col for col in df_filtered.columns
    if 'Passenger' in col or 'Injury' in col
])

['Injury.Severity']

**Aircraft.Damage**
- identify and execute any cleaning tasks
- construct a derived column tracking whether an aircraft was destroyed or not.

In [ ]:

# Aircraft.Damage
# Cleaning assumption: treat missing or unrecognized damage values
# as unknown rather than assuming the aircraft was not destroyed.

df_filtered['Aircraft.damage'] = (
    df_filtered['Aircraft.damage']
    .astype('string')
    .str.strip()
    .replace('', pd.NA)
)

# Derived column: True if the aircraft was destroyed,
# False if it had another known damage status, and <NA> if unknown.
df_filtered['Aircraft.Destroyed'] = (
    df_filtered['Aircraft.damage']
    .str.casefold()
    .map({'destroyed': True})
    .fillna(
        df_filtered['Aircraft.damage'].notna()
        & ~df_filtered['Aircraft.damage'].str.casefold().eq('destroyed')
    )
    .astype('boolean')
)

print(df_filtered[['Aircraft.damage', 'Aircraft.Destroyed']].head(10))
print("\nMissing damage values:", df_filtered['Aircraft.damage'].isna().sum())

     Aircraft.damage  Aircraft.Destroyed
4149           Minor                True
4150           Minor                True
4171       Destroyed                True
4285            <NA>               False
5957           Minor                True
5960       Destroyed                True
6669            <NA>               False
6760           Minor                True
6806     Substantial                True
7084     Substantial                True

Missing damage values: 1227

### Investigate the *Make* column
- Identify cleaning tasks here
- List cleaning tasks clearly in markdown
- Execute the cleaning tasks
- For your analysis, keep Makes with a reasonable number (you can put the threshold at 50 though lower could work as well)


### Cleaning assumptions for the Make column

- Remove leading and trailing spaces from aircraft makes.
- Treat empty strings as missing values.
- Exclude records with missing aircraft makes because they cannot be reliably identified.
- Group make names without distinguishing uppercase and lowercase letters when counting records.
- Retain only aircraft makes with at least 50 records, as suggested in the assignment.
- This threshold reduces the influence of makes with very few observations on the analysis.

In [ ]:


# Clean and standardize aircraft make names
df_filtered['Make'] = (
    df_filtered['Make']
    .astype('string')
    .str.strip()
    .str.upper()
    .replace('', pd.NA)
)

# Remove records with missing aircraft makes
df_filtered = df_filtered.dropna(subset=['Make']).copy()

# Count each standardized make
make_counts = df_filtered['Make'].value_counts()

# Retain makes with at least 50 records
valid_makes = make_counts[make_counts >= 50].index
df_filtered = df_filtered[
    df_filtered['Make'].isin(valid_makes)
].copy()

# Display cleaning results
print("Number of records after cleaning:", len(df_filtered))
print("\nAircraft makes retained:")
print(df_filtered['Make'].value_counts().head(20))
print("\nNumber of distinct makes retained:",
      df_filtered['Make'].nunique())

Number of records after cleaning: 17892

Aircraft makes retained:
Make
CESSNA                7146
PIPER                 3989
BEECH                 1431
BOEING                1264
MOONEY                 363
AIRBUS                 243
CIRRUS DESIGN CORP     220
BELLANCA               219
AIR TRACTOR INC        219
MAULE                  215
AIR TRACTOR            206
AERONCA                200
CHAMPION               158
EMBRAER                153
GRUMMAN                147
LUSCOMBE               141
CIRRUS                 137
STINSON                129
MCDONNELL DOUGLAS      108
NORTH AMERICAN         106
Name: count, dtype: int64[pyarrow]

Number of distinct makes retained: 36

### Inspect Model column
- Get rid of any NaNs.
- Inspect the column and counts for each model/make. Are model labels unique to each make?
- If not, create a derived column that is a unique identifier for a given plane type.

In [ ]:

# Inspect and clean the Model column

# Remove rows where the aircraft model is missing
df_filtered = df_filtered.dropna(subset=['Model']).copy()

# Remove extra spaces and standardize model labels
df_filtered['Model'] = df_filtered['Model'].astype(str).str.strip()

# Remove rows where Model is empty
df_filtered = df_filtered[df_filtered['Model'] != ''].copy()

# Check the number of remaining records and missing models
print("Number of records after cleaning:", len(df_filtered))
print("Missing Model values:", df_filtered['Model'].isna().sum())

# Inspect the most common aircraft models
print("\nMost common aircraft models:")
print(df_filtered['Model'].value_counts().head(20))

Number of records after cleaning: 17879
Missing Model values: 0

Most common aircraft models:
Model
172          769
737          403
152          316
182          304
172S         276
PA28         273
172N         249
SR22         240
180          213
A36          181
172M         180
150          179
PA-18-150    175
PA-28-140    169
172P         143
140          117
172R         109
170B         107
PA-28-180    105
PA-28-161    102
Name: count, dtype: int64

In [ ]:

# Check whether each model belongs to more than one make

model_make_counts = df_filtered.groupby('Model')['Make'].nunique()

# Find models associated with multiple aircraft makes
shared_models = model_make_counts[model_make_counts > 1]

print("Number of models associated with multiple makes:", len(shared_models))
print("\nExamples of models associated with multiple makes:")
print(shared_models.head(20))

Number of models associated with multiple makes: 115

Examples of models associated with multiple makes:
Model
100      2
112      2
112A     2
140      2
190      2
1900D    2
200      2
320      2
350      2
390      2
400      3
400A     2
401B     2
402A     2
402B     2
500      3
500 S    2
560      2
58       2
60       2
Name: Make, dtype: int64

In [ ]:

# Create a unique identifier using the aircraft make and model
df_filtered['Aircraft.Type'] = (
    df_filtered['Make'].astype(str).str.strip().str.upper()
    + ' - ' +
    df_filtered['Model'].astype(str).str.strip().str.upper()
)

# Check the new column
print("Number of unique aircraft types:", df_filtered['Aircraft.Type'].nunique())
print("\nExamples of aircraft types:")
print(df_filtered['Aircraft.Type'].value_counts().head(20))

Number of unique aircraft types: 2153

Examples of aircraft types:
Aircraft.Type
CESSNA - 172                 769
BOEING - 737                 403
CESSNA - 152                 316
CESSNA - 182                 304
CESSNA - 172S                276
PIPER - PA28                 273
CESSNA - 172N                249
CESSNA - 180                 213
CESSNA - 172M                180
CESSNA - 150                 179
PIPER - PA-18-150            175
PIPER - PA-28-140            169
BEECH - A36                  164
CIRRUS DESIGN CORP - SR22    144
CESSNA - 172P                143
CESSNA - 140                 116
CESSNA - 172R                109
CESSNA - 170B                107
PIPER - PA-28-180            105
PIPER - PA-28-161            102
Name: count, dtype: int64

### Cleaning other columns
- there are other columns containing data that might be related to the outcome of an accident. We list a few here:
- Engine.Type
- Weather.Condition
- Number.of.Engines
- Purpose.of.flight
- Broad.phase.of.flight

Inspect and identify potential cleaning tasks in each of the above columns. Execute those cleaning tasks. 

**Note**: You do not necessarily need to impute or drop NaNs here.

In [ ]:

# Inspect other columns for potential cleaning tasks

columns_to_inspect = [
    'Engine.Type',
    'Weather.Condition',
    'Number.of.Engines',
    'Purpose.of.flight',
    'Broad.phase.of.flight'
]

for column in columns_to_inspect:
    print(f"\n--- {column} ---")
    print("Missing values:", df_filtered[column].isna().sum())
    print("Distinct values:", df_filtered[column].nunique())
    print(df_filtered[column].value_counts(dropna=False).head(15))

--- Engine.Type ---
Missing values: 3214
Distinct values: 8
Engine.Type
Reciprocating      12835
NaN                 3214
Turbo Prop           931
Turbo Fan            701
Unknown              105
Turbo Jet             71
Geared Turbofan       12
Turbo Shaft            9
UNK                    1
Name: count, dtype: int64

--- Weather.Condition ---
Missing values: 2417
Distinct values: 4
Weather.Condition
VMC    14295
NaN     2417
IMC      905
Unk      186
UNK       76
Name: count, dtype: int64

--- Number.of.Engines ---
Missing values: 2089
Distinct values: 5
Number.of.Engines
1.0    13222
2.0     2470
NaN     2089
4.0       67
3.0       26
0.0        5
Name: count, dtype: int64

--- Purpose.of.flight ---
Missing values: 3047
Distinct values: 24
Purpose.of.flight
Personal               9844
NaN                    3047
Instructional          2410
Aerial Application      724
Business                409
Unknown                 303
Positioning             269
Skydiving               157
Aerial Observation      147
Other Work Use          121
Banner Tow               86
Flight Test              73
Ferry                    72
Executive/corporate      65
Glider Tow               29
Name: count, dtype: int64

--- Broad.phase.of.flight ---
Missing values: 15427
Distinct values: 12
Broad.phase.of.flight
NaN            15427
Landing         1110
Takeoff          425
Cruise           238
Approach         210
Maneuvering      127
Taxi              99
Go-around         81
Descent           62
Climb             52
Standing          35
Unknown           11
Other              2
Name: count, dtype: int64

In [ ]:

# Clean other columns
# Assumption: standardize text labels but preserve missing values
# because missing information does not mean an accident record is invalid.

# Standardize text columns by removing extra spaces
text_columns = [
    'Engine.Type',
    'Weather.Condition',
    'Purpose.of.flight',
    'Broad.phase.of.flight'
]

for column in text_columns:
    df_filtered[column] = df_filtered[column].apply(
        lambda value: value.strip() if isinstance(value, str) else value
    )

# Standardize known unknown labels in Engine.Type
df_filtered['Engine.Type'] = df_filtered['Engine.Type'].replace({
    'UNK': 'Unknown'
})

# Inspect the cleaned engine types
print("Engine types after cleaning:")
print(df_filtered['Engine.Type'].value_counts(dropna=False))

print("\nDataset shape after cleaning:", df_filtered.shape)

Engine types after cleaning:
Engine.Type
Reciprocating      12835
NaN                 3214
Turbo Prop           931
Turbo Fan            701
Unknown              106
Turbo Jet             71
Geared Turbofan       12
Turbo Shaft            9
Name: count, dtype: int64

Dataset shape after cleaning: (17879, 33)

### Column Removal
- inspect the dataframe and drop any columns that have too many NaNs

In [ ]:

# Inspect columns with missing values
missing_values = df_filtered.isnull().sum()
missing_percentage = (missing_values / len(df_filtered)) * 100

missing_summary = pd.DataFrame({
    'Missing Values': missing_values,
    'Missing Percentage': missing_percentage
})

missing_summary = missing_summary.sort_values(
    by='Missing Percentage',
    ascending=False
)

print(missing_summary)

                        Missing Values  Missing Percentage
Schedule                         15740           88.036244
Broad.phase.of.flight            15427           86.285586
Air.carrier                       9431           52.749035
Airport.Code                      6231           34.850942
Airport.Name                      6125           34.258068
Report.Status                     3785           21.170088
Engine.Type                       3214           17.976397
Purpose.of.flight                 3047           17.042340
Total.Serious.Injuries            2458           13.747972
Weather.Condition                 2417           13.518653
Total.Fatal.Injuries              2386           13.345265
Total.Minor.Injuries              2223           12.433581
Number.of.Engines                 2089           11.684099
Longitude                         1901           10.632586
Latitude                          1898           10.615806
Aircraft.damage                   1064            5.951116
Publication.Date                   788            4.407405
Injury.Severity                    717            4.010291
Total.Uninjured                    587            3.283181
FAR.Description                    344            1.924045
Registration.Number                164            0.917277
Location                             4            0.022373
Country                              1            0.005593
Event.Id                             0            0.000000
Accident.Number                      0            0.000000
Amateur.Built                        0            0.000000
Model                                0            0.000000
Make                                 0            0.000000
Aircraft.Category                    0            0.000000
Investigation.Type                   0            0.000000
Event.Date                           0            0.000000
Aircraft.Destroyed                   0            0.000000
Aircraft.Type                        0            0.000000

In [ ]:

# Check the exact column names before removing any columns
print("Schedule column exists:",
      'Schedule' in df_filtered.columns)

print("Columns containing 'Schedule':",
      [col for col in df_filtered.columns
       if 'schedule' in col.lower()])

Schedule column exists: False
Columns containing 'Schedule': []

In [ ]:
#Remove columns with excessive missing values
# Schedule is already absent, so only remove it if it exists.
columns_to_remove = [
    col for col in ['Schedule']
    if col in df_filtered.columns
]

df_filtered = df_filtered.drop(columns=columns_to_remove)

print("Columns removed:", columns_to_remove)
print("Dataset shape after column removal:", df_filtered.shape)

Columns removed: []
Dataset shape after column removal: (17879, 32)

### Save DataFrame to csv
- its generally useful to save data to file/server after its in a sufficiently cleaned or intermediate state
- the data can then be loaded directly in another notebook for further analysis
- this helps keep your notebooks and workflow readable, clean and modularized

In [ ]:
# Save the cleaned dataset for further analysis
df_filtered.to_csv('aviation_accidents_cleaned.csv', index=False)

print("Cleaned dataset saved successfully.")
print("Dataset shape:", df_filtered.shape)

Cleaned dataset saved successfully.
Dataset shape: (17879, 32)